// Generated by CoffeeScript 1.3.3
(function() {
  var root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.next = function(name) {
    var words;
    clearInterval(root.playInterval);
    $(name).animate({
      top: "-=" + $(name).css('line-height')
    }, 'fast');
    root.string++;
    words = root.strings[root.string].split(' ');
    words = words.filter(function(e) {
      return e;
    });
    root.playInterval = root.setInterval("next('" + name + "')", 60000 * words.length / $('#speed').val());
    return true;
  };

  root.playInterval = 0;

  root.string = 0;

  root.strings = $('output pre').html().split('\n');

  $('.play').live('click', function(event) {
    var words;
    $('.play').addClass('pause');
    $('.play').text('Pause');
    $('.play').removeClass('play');
    words = root.strings[root.string].split(' ');
    words = words.filter(function(e) {
      return e;
    });
    root.playInterval = root.setInterval("next('output pre')", 60000 * words.length / $('#speed').val());
    return false;
  });

  $('.pause').live('click', function(event) {
    clearInterval(root.playInterval);
    $('.pause').addClass('play');
    $('.pause').text('Play');
    $('.pause').removeClass('pause');
    return false;
  });

}).call(this);
